### ISSUE TITLE
REQUEST: add option to search installed packages

### ISSUE THREAD

**Issue by xxxserxxx** [TheCycoONE/pacpreview#2]
The use case that led me to pacpreview was cleaning out packages I don't use; something like:
```
yay -Qsq | fzf --multi --preview 'pacpreview {1}' | xargs -ro yay -Rnsu
```
So I'd like to see the info for the installed package. If the package came from AUR, or I just created a PKGBUILD and installed something manually to have it tracked by pacman, then pacpreview won't find the information.

I'd like to be able to pass an argument that tells pacpreview to use the information from the installed package, rather than the repo; then I would always get info.

*Alternatively*, if pacpreview can't find the package, fall back and use the locally installed package info, and only if **that** isn't found, then report `No package found`.

**Comment by TheCycoONE** [comment]
Implemented the alternate solution mentioned here.
